---
root: true
env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
ignorePatterns:
  - dist
parser: '@typescript-eslint/parser'
plugins:
  - react-refresh
rules:
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
  quotes:
    - 2
    - single
    - avoidEscape: true
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: true
      warnOnUnassignedImports: true
